### PR TITLE
Add RISC-V target

### PR DESCRIPTION
**Pull request by jerryz123**

### CODE REVIEW

**Comment by arkhadem** [comment]
Hi Jerry,

Thanks for working on Swan. If you just change the LOCAL_CPP to riscv64-unknown-elf-g++ in the Makefile for the RISC-V compilation, it does not work? I'd like to know the reason for all those changes in the Makefile.

Best

**Comment by jerryz123** [comment]
I was following the pattern set by `local` and `phone`, where I interpret the pattern to be: 
 - `local` - native host compile
 - `phone` - cross-compile for ARM

Thus, I added 
 - `riscv` - cross-compile for RISC-V
 
If RVV kernels are added, then the `riscv` target could be used to select those implementations instead of the current `scalar` or `neon` implementations.

**Comment by arkhadem** [comment]
Makes sense. I merged the PR. Thanks for your time.

Do you have any plans to add the RVV kernels? I am not actively working on that but it would be an interesting project. Most libraries are taken from the Chromium project but I did not find any RVV implementations. So we need to implement the RVV ourselves.

**Comment by jerryz123** [comment]
Thanks for merging this. 

I am investigating the possibility of adding RVV. These kernels would need to be implemented by hand using intrinsics.

**Comment by arkhadem** [comment]
I can also help you with that. Contact my email address if you decide to do so. Thanks.

**Pull request merged**
